### ISSUE TITLE
EDS Caching/Server Configurations

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1558] opened 2017-08-07 22:47 UTC
If we end up using EDS caching in production, we'll want to configure the cache to be stored somewhere that won't fill up quickly (we will clear the cache hourly, but still).

We may also want to configure the cache to be somewhere that is shared between the web-app nodes so that the cached content isn't fragmented across nodes.

The relevant `Settings` are `EDS_CACHE ` and `EDS_CACHE_DIR`.

**Comment by thatbudakguy** [comment] 2023-03-22 21:58
duplicate of #1742, seems like

**Closed by thatbudakguy** 2023-03-22 21:58 UTC
Labels: 3.2
