### ISSUE TITLE
"More options" line breaks not present on bs4 branch

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3644] opened 2023-10-18 18:13 UTC
Production
<img width="796" alt="Screen Shot 2023-10-18 at 2 11 48 PM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/45ec2aa5-fe1a-438a-9091-16d0a6cb1252">

Stage/BS4
<img width="615" alt="Screen Shot 2023-10-18 at 2 11 32 PM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/858eff18-2afb-4bdd-966a-e209b4ac823f">

**Comment by corylown** [comment] 2023-11-06 22:12
Duplicate of #3670. Closing this in favor of issue that references current production.

**Closed by corylown** 2023-11-06 22:12 UTC
