### ISSUE TITLE
Click on rosette in Bento banner should go to http://library.stanford.edu

### ISSUE THREAD

**Issue by snydman** [sul-dlss/SearchWorks#1812] opened 2017-09-22 21:21 UTC
Currently goes to http://library.stanford.edu/all

Should go to http://library.stanford.edu

![image](https://user-images.githubusercontent.com/3279382/30764771-5173f35e-9fa1-11e7-84b9-44fc99d26f51.png)

**Comment by jkeck** [comment] 2017-09-22 21:38
Duplicate of #1809

**Closed by jkeck** 2017-09-22 21:38 UTC
