### ISSUE TITLE
At narrow viewports the border-bottom on .results-metadata-section runs through the cover thumbnail

### ISSUE THREAD

**Issue by corylown** [sul-dlss/SearchWorks#3006] opened 2022-09-07 17:51 UTC
<img width="430" alt="Screen Shot 2022-09-07 at 1 47 39 PM" src="https://user-images.githubusercontent.com/458247/188945535-00e169a6-0436-46ee-8db3-bbf8ce254a92.png">

**Comment by cbeer** [comment] 2022-09-07 21:21
Duplicate of #2544 😬

**Closed by cbeer** 2022-09-07 21:21 UTC
