### ISSUE TITLE
[SearchWorks/production] EBSCO::EDS::BadRequest: {"DetailedErrorDescription"=>"", "ErrorDescription"=>"Unknown error encountered", "ErrorNumber"=>"106"}

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#1749] opened 2017-09-11 13:32 UTC
## Backtrace

    line 7 of [PROJECT_ROOT]/app/models/eds/session.rb: search
    line 26 of [PROJECT_ROOT]/app/models/eds/repository.rb: eds_search
    line 5 of [PROJECT_ROOT]/app/models/eds/repository.rb: block in search

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50022/faults/34623925)

**Comment by drh-stanford** [comment] 2017-09-11 18:33
duplicate of #1752

**Closed** 2017-09-11 22:58 UTC
Labels: 3.2
