### ISSUE TITLE
Contributor search doesn't find results when minus sign in 7xx field

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2770] opened 2021-12-01 20:07 UTC
Jeanette reported that clicking the Contributor link on this record yields zero search results: https://searchworks.stanford.edu/view/12129078

Gryphon core thought this might have to do with the minus sign in d| of the 700.  Shelley in particular thought that the minus sign seemed to be removing any of the data after it and therefore no search results.  

Another example record with two Contributors, one with a minus (and zero search results) and one without a minus (and successful search results):https://searchworks.stanford.edu/view/8576697 

Jira ticket: https://jirasul.stanford.edu/jira/browse/SW-4061

**Comment by corylown** [comment] 2021-12-01 21:53
It's suspicious that contributors are wrapped twice in double quotes and authors are not. I think this will result in unexpected query parsing by Solr (and the minus prefix would be interpreted as NOT rather than part of the quoted query). Both SearchWorks and Traject are adding quotes around contributors, but only SearchWorks is wrapping quotes around authors. I suspect we want to remove the quotes being adding via Traject?

- Template in SearchWorks that renders the click to search links under Authors/Contributors: https://github.com/sul-dlss/SearchWorks/blob/master/app/views/marc_fields/_linked_author.html.erb#L5
- Quotes being added to contributors via Traject: https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/sirsi_config.rb#L807
- SolrDocument example that shows that contributors are quoted in the SolrDocument while authors are not:
- https://searchworks.stanford.edu/view/12129078.json

<img width="631" alt="Screen Shot 2021-12-01 at 4 47 08 PM" src="https://user-images.githubusercontent.com/458247/144319667-75fc692e-cee6-479e-8c56-fff864871bdb.png">

**Comment by corylown** [comment] 2021-12-02 20:08
Proposed fix in `searchworks_traject_indexer`: https://github.com/sul-dlss/searchworks_traject_indexer/pull/577

**Comment by corylown** [comment] 2021-12-02 20:28
The change to `searchworks_traject_indexer` that removes quotes from the contributors search value in `author_struct` is merged into the master branch. This will be deployed to production with dependency updates on 12/6/2021. For the fix to be applied all impacted records will need to be re-indexed. I believe a full dump/index will happen later this month.

**Comment by saseestone** [comment] 2021-12-02 22:09
Thanks Cory!  And having the deploy details here is really terrific.  Thanks!

**Comment by corylown** [comment] 2022-01-07 14:30
Closing this issue because I've confirmed that the fix works as expected. Some records may still need to be re-indexed for the fix to be applied in production, but recently indexed records are correct.

**Closed by corylown** 2022-01-07 14:30 UTC
