### ISSUE TITLE
Bootstrap modal z-index issue

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1004] opened 2015-01-29 19:45 UTC
After upgrading from Bootstrap 3.2 to 3.3 the overlay behind the modal would prevent from clicking the model content (and therefore closing the modal when clicking on the overlay) seemingly in production mode only.  The bootstrap example docs appear to have a z-index set on the modal dialog while it's not for us.

We've explicitly added a z-index in 4498fa4f0d1cfbea321590c25c4ae51c2bdecb35 but should figure out why exactly this is happening and remove our z-index override.

**Comment by marlo-longley** [comment] 2022-08-12 22:27
I am having trouble reproducing this. The ticket says the issue is only happening in production so it's possible my local testing is irrelevant. I tested this using the Librarian View modal.

But-- I looked into the Bootstrap 3.3.0 docs/code/demos (the version referenced above) and did not see a `z-index` set on the `.modal-dialog` class. There is a `z-index` set on the parent `.modal` class. Locally, if I remove our override from https://github.com/sul-dlss/SearchWorks/commit/4498fa4f0d1cfbea321590c25c4ae51c2bdecb35 , I have no problems and can properly click the modal content and close the modal. The `z-index` from the parent  `.modal` class works. 

It's possible that [changes](https://github.com/twbs/bootstrap/compare/v3.3.0...v3.4.1) between Bootstrap 3.3.0 referenced above, and 3.4.1 which we now ship with SearchWorks, this issue was resolved. [This commit](https://github.com/twbs/bootstrap/commit/14e5fb04e9bf7c406b799b75b0427522d87a4ccb) from 2014 seems to have caused issues for folks who use Bootstrap CSS, but not JS. It was [fixed in March 2015 ](https://github.com/twbs/bootstrap/pull/15881) after this ticket was filed. I believe we can remove this workaround.

I don't know how to test the "production only" element of this reported bug without pushing a change to production.

**Closed** 2022-08-12 22:49 UTC
Labels: Technical Debt
