### ISSUE TITLE
SW Solr Users feedback: Uncertain byte for byte matching, CJK

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1923] opened 2018-08-22 18:09 UTC
Reported issue: In a Title search 佛教學 (the study of Buddhism) retrieves 658 records in old system, but only 12 in new system. At least 9 of the records on the first page of the old system result set are not in the new system’s result set at all (e.g. 2, 4-7, 11, 12, 13, 17). https://sw-relevancy-new.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search_title&q=%E4%BD%9B%E6%95%99%E5%AD%B8	

Discussion: Second character in that string is in our special library for converting traditional chinese to other traditional Chinese; in current form, its a dictionary word in that trigram; in metadata we have, it looks the same but isn't and isn't in the dictionary we aren't using; 

Question for Vitus or others in follow-up: are these characters the same? These are either a data problem or a character mappings concern.

**Comment by cbeer** [comment] 2018-08-22 22:34
Should be fixed by a custom character transform that applies Stanford's CJK normalization rules; spot-checking some records, there's some interesting new bigrams from our metadata which might need additional analysis.

**Comment by cbeer** [comment] 2018-08-24 15:14
With sul-dlss/sul-solr-configs#141, we now retrieve 211 results in the new system, including many that were missing from the first page before.

I still need to have that follow up conversation to confirm the meaning of 佛教學 vs 佛敎學報 (#2 in -current, missing in -new, because the metadata value is turned into two bigrams instead of a unigram and a bigram).

**Comment by cbeer** [comment] 2018-08-29 21:01
Duplicate of https://github.com/sul-dlss/sw_index_tests/issues/206. The new behavior is probably acceptable.

**Closed by cbeer** 2018-08-29 21:01 UTC
