### ISSUE TITLE
"Extra" call numbers listed in Call Number browse

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#4003] opened 2024-02-22 06:56 UTC
Jeanette has reported examples of records that show "extra" starting call numbers in the call number browse. She's identified two scenarios where this is happening.

### Problem no. 1: We're showing two identical call numbers, and it's not apparent why. 
In each example we've found, the first call number displays a portion of the browse ribbon that is incorrect.  

Example: https://searchworks.stanford.edu/view/3998525

Screen shot after selecting the first call number. Note there is no red outline on any of the titles listed in the browse, and we're not displaying the correct position for the call number of the title. 

<img width="841" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/5896867b-3451-4142-9575-2d9f15087751">

It's easier to see we're displaying the wrong position when you "view full page":
<img width="553" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/1cc1465a-100d-4115-9dd0-a0378ad66362">

Screen shot of the second call number. The red outline appears on the correct title record, and we're displaying the correct position.
<img width="821" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/568dca72-b233-46dd-8f34-5a856cff446b">

So we've got it right on the second call number. The question is why are we displaying the first call number (and incorrectly positioned)?

Here's another example record: https://searchworks.stanford.edu/view/737809

### Problem no. 2: We're not "lopping" the call number when we should.
In at least one example, we're not "lopping" off portions of the call number (e.g "HEFT" in the example record provided) for call number browse. 

Example record: 
- https://searchworks.stanford.edu/view/8810055

<img width="630" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/0d493377-c53f-4927-a34d-079a25b785f5">

 When the user clicks on each call number listed, the same title displays over and over again (in the same position). Chris has indicated that we're still using Symphony logic to manage call number lopping.  Can we use FOLIO to help us manage this better (i.e. display only one call number)? 

### Reminder that we do have instances that have more than one call number type.
In these instances, we definitely need to keep displaying both in the call number browse. 
Example:  https://searchworks.stanford.edu/view/5802108

Adding in the SW JIRA tickets where this was reported: [SW-4294](https://jirasul.stanford.edu/jira/browse/SW-4294), [SW-4285](https://jirasul.stanford.edu/jira/browse/SW-4285), [SW-3973](https://jirasul.stanford.edu/jira/browse/SW-3973)

**Comment by saseestone** [comment] 2024-02-22 07:09
Another record that may be another flavor of Problem no. 2 (call number lopping). https://searchworks.stanford.edu/view/520112

If you click on the call number ending with "STATUTES" you see the red outline around a title that ends in "INDEX". If you click on the call number ending with "INDEX", you see the red outline around a title that ends in "STATUTES". If you look really closely, you realize that the red outline is drawn around a title that is in exactly the same place (in relationship to the other titles listed before and after) :headspin:

**Comment by cbeer** [comment] 2024-02-23 00:43
I did a quick comparison between our current LC lopping with FOLIO's base call number for an item and I think it's plausible to use the base number to drive the browse panel. The FOLIO call numbers are generally lopped more aggressively but I think generally more accurately.

The only place where the base call number seems like it could be problematic is when multiple instances have the same base call number. I think this is a relatively rare case (but seems to happen more in microform/microfiche, e.g. https://searchworks.stanford.edu/view/6203864). It's probably worth figuring out a way to see how many non-unique call numbers are out there.

**Comment by jcoyne** [comment] 2024-02-23 18:39
The first problem is here:

https://github.com/sul-dlss/SearchWorks/blob/main/app/views/catalog/record/_callnumber_browse.html.erb#L8-L11

we are looking for items (in `item_display_struct`) that have a unique `lopped_callnumber`

The `(lopped_callnumber, callnumber)` sets include `("B945 .D41 H53 1998 ...", "B945 .D41 H53 1998 V.1")` and `("B945 .D41 H53 1998 V.1", "B945 .D41 H53 1998 V.1")`. So, different `lopped_callnumbers` with the same `callnumber`

**Comment by dnoneill** [comment] 2024-02-26 23:15
Based on @jcoyne's comment and my investigation that does seem to be the issue. What is the reason for  ' ...' being added to the shelf key?

**Comment by dnoneill** [comment] 2024-02-27 18:09
I looked into this, the larger problem is B945 .D41 H53 1998 V.1 is not getting lopped. Everything else has the version lopped off.

**Comment by cbeer** [comment] 2024-02-27 18:19
>  the larger problem is B945 .D41 H53 1998 V.1 is not getting lopped

I think this is something the FOLIO call numbers would help with, with some caveats about the differences between how we're lopping call numbers and how they appear in FOLIO:
https://github.com/sul-dlss/SearchWorks/issues/4003#issuecomment-1960580804

I did dump all the FOLIO holdings call numbers and there's a group of ~35k records where FOLIO's call number could change stuff.

**Comment by cbeer** [comment] 2024-02-27 19:30
I talked to @saseestone about how we think call number browse should work (and those 35k weird call numbers) and I think we're ok to use the FOLIO holding's call numbers to replace our custom call number lopping.

I think the expected behavior is:
- for each instance, each unique FOLIO holdings call number (or the browse call number from the 050/090 for e-resources)  should be represented by an entry in the browse nearby
- we select a representative item for each call number; serials pick the most recent item, and everything else picks the earliest.. and we use that call number (and its shelfkey) for sorting the browse nearby list.

This means we get to ignore all the lopping logic, looking for multiple holdings, etc that's currently going on. I think this fixes the duplicate call numbers from the ticket at least.

**Comment by cbeer** [comment] 2024-03-05 18:14
I think these problems are fixed by #4073 (etc).

**Closed by cbeer** 2024-03-05 18:14 UTC

**Comment by cbeer** [comment] 2024-03-06 16:30
Here's a sampling of the browse nearby changes currently in -test:

- https://searchworks-stage.stanford.edu/view/2024710 (correctly lops V.1, V.2, etc from Tanner call numbers)
- https://searchworks.stanford.edu/view/2004046 (fails to lop Tanner call number 😢 )
- https://searchworks.stanford.edu/view/2090809 (sorts in a different location.. presumably better because it used to sort on `other serial great britain ...` and now sorts on `other serial great britain zzyqqv~7la}zzzzzy~zzzzyz~~~~~~~~~~~~~~~~~~~~~~~~~~`)
- https://searchworks.stanford.edu/view/200198 (not sure why the call number changed.. but it's a FOLIO data problem 🤞 )
- https://searchworks.stanford.edu/view/2000410 (claims to be LC, but isn't.. we aren't showing the call number browse in either case so no harm)
- https://searchworks.stanford.edu/view/200467 (another funky not-quite-LC)
- https://searchworks-stage.stanford.edu/view/2028136 (not sure what's going on here.. it wasn't good before and still isn't)
- https://searchworks.stanford.edu/view/2018731 (also not good before, but at least browse nearby is working better)
- https://searchworks.stanford.edu/view/2085169 (not sure how the call numbers were lopped before or how it picked only one 🤷‍♂️ )
- https://searchworks.stanford.edu/view/2049177 (we're now sorting the reels in order, yay)
- https://searchworks.stanford.edu/view/206277 (we used to lop to just 2 browsable call numbers, but now there are three)
- https://searchworks.stanford.edu/view/205755 (used to lop to 1, now there's two)
- https://searchworks.stanford.edu/view/200856 (used to show all 3, now we lop to 1. win some/lose some?)
- https://searchworks.stanford.edu/view/2008220 (used to show 1, now shows 2.. but at least browse nearby is sorted sensibly?)
- https://searchworks.stanford.edu/view/2046450 (didn't show browse nearby, still don't.. but I wonder if we're not parsing LAW LCs correctly?)
- https://searchworks.stanford.edu/view/2006405 (don't understand the current sort order)
- https://searchworks.stanford.edu/view/2025430 (seem to now be doing a better job lopping + sorting)
- https://searchworks.stanford.edu/view/2040478 (not sure what's going on in browse before or after).
- https://searchworks.stanford.edu/view/2040563 (has an extra button in -stage. weird?)
