### ISSUE TITLE
Righthand sidebar minimap navigation has buggy collapse/expand behaviour

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#973] opened 2014-10-24 23:35 UTC
The sidebar nav buttons appear as blank buttons to a screen reader. The text is toggling between display:none and display:inline.

We can either include duplicate .sr-only text, or instead of display:none, use an absolute offscreen position. (The latter seems more efficient.)

(Is it useful to compare how we did the skip links to display on focus?)

**Comment by jkeck** [comment] 2015-11-03 23:59
https://github.com/sul-dlss/SearchWorks/blob/master/app/views/catalog/record/_record_side_nav.html.erb

https://github.com/sul-dlss/SearchWorks/blob/master/app/views/catalog/record/_marc_metadata_sections.html.erb#L2-L17

**Comment by aeschylus** [comment] 2015-11-11 23:01
The problem is with [this hover event](https://github.com/sul-dlss/SearchWorks/blob/73bf7b875cc15b886679c4a3a9744ea43eaa2f96/app/assets/javascripts/jquery.record-side-nav.js#L59-L61). Scrolling also closes it. And there doesn't seem to be any css expanding the buttons.

I can fix this pretty easily if I can get Searchworks running again.

**Comment by aeschylus** [comment] 2015-11-12 00:13
See #1098

**Comment by aeschylus** [comment] 2016-01-21 01:03
Should be closed by https://github.com/sul-dlss/SearchWorks/pull/1149.

**Comment by aeschylus** [comment] 2016-01-26 19:24
Closed by PR #1149

**Closed by aeschylus** 2016-01-26 19:24 UTC
Labels: accessibility, in progress
